# Generated by Django 4.0.1 on 2022-01-18 02:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(error_messages={'unique': 'Telefone já cadastrado'}, max_length=16, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=150)),
                ('CEP', models.CharField(max_length=9)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(error_messages={'unique': 'Email já cadastrado'}, max_length=200, unique=True)),
                ('senha', models.CharField(max_length=16)),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_agendamento', models.CharField(choices=[('AC', 'A comfirmar'), ('C', 'Comfirmado'), ('F', 'Finalizado')], default='AC', max_length=2)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('descricao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalApp.paciente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalApp.usuario')),
            ],
        ),
    ]
