# Generated by Django 4.0.1 on 2022-01-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status_agendamento',
            field=models.CharField(choices=[('AC', 'A confirmar'), ('C', 'Confirmado'), ('F', 'Finalizado')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='UF',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(error_messages={'unique': 'Email já cadastrado'}, max_length=150, unique=True),
        ),
    ]
